Add a some doc about WebWalletLoginButton
multiversx/mx-sdk-dapp pull request #601
Opened 2023-01-30 23:42 UTC by blablalf

2023-02-01 09:15 UTC, CiprianDraghici requested changes

2023-02-01 09:15 UTC, CiprianDraghici commented on README.md
>      <TransactionsToastList
Please replace `<TransactionsToastList ... />` with 
```
// all properties are optional
<TransactionsToastList
      className = 'transactions-toast-list'
      transactionToastClassName="transactions-toast-class"
      successfulToastLifetime={30000}
      parentElement={
        /*
          React NodeElement where the toast will be rendered
         */
      }
    />
```

2023-02-02 09:00 UTC, CiprianDraghici approved these changes

2023-02-02 09:00 UTC, arhtudormorar approved these changes

2023-02-02 09:00 UTC, merged