add webview provider to be able to integrate dapps into xPortal
multiversx/mx-sdk-dapp pull request #609
Opened 2023-02-02 15:13 UTC by StanislavSava

This PR adds the ability to support a webview provider, to allow dApp to add support for xPortal HUB integration

2023-02-02 15:18 UTC, arhtudormorar commented on src/hooks/login/useWebViewLogin.ts
> +  function webviewLogin() {
const

2023-02-02 15:18 UTC, arhtudormorar commented on src/providers/webviewProvider/webviewProvider.ts
> +      // reject("TODO: implement");
comment

2023-02-02 15:18 UTC, arhtudormorar commented on src/providers/webviewProvider/webviewProvider.ts
> +                if (!error) {
if error return early

2023-02-02 15:18 UTC, arhtudormorar commented on src/providers/webviewProvider/webviewProvider.ts
> +export default webviewProvider;
no export default

2023-02-02 15:18 UTC, arhtudormorar commented on src/utils/platform/detectCurrentPlatform.ts
> +export function detectCurrentPlatform() {
const

2023-02-02 15:18 UTC, arhtudormorar commented on src/wrappers/DappProvider/index.tsx
>    dappConfig
shouldUseWebViewProvider shoud go into `dappConfig`

2023-02-02 15:23 UTC, CiprianDraghici commented on src/providers/webviewProvider/requestMethods.ts
> +export const requestMethods = {
I think you should set the targetOrigin for each post message and you should accept the message just from the desired origins (you should whitelisting the origins in your client)

2023-02-02 15:24 UTC, CiprianDraghici commented on src/providers/webviewProvider/webviewProvider.ts
> +            let eventData = event.data;
here you should accept the message only from accepted origins

2023-02-02 16:21 UTC, StanislavSava commented on src/providers/webviewProvider/webviewProvider.ts
> +                if (!error) {
aci e if (resolve) else reject

2023-02-02 16:32 UTC, CiprianDraghici commented on src/components/ProviderInitializer.tsx
> +  useWebViewLogin();
I'd use a condition here to not use this hook for all dApp, just if you need this. The condition cand be added on DappProvider

2023-02-02 16:35 UTC, CiprianDraghici commented on src/providers/webviewProvider/webviewProvider.ts
> +                reject('Unable to liogin');
typo here: `liogin`

2023-02-02 16:36 UTC, CiprianDraghici commented on src/providers/webviewProvider/webviewProvider.ts
> +      console.log('error loggin in', err);
typo here

2023-02-02 16:37 UTC, CiprianDraghici commented on src/providers/webviewProvider/webviewProvider.ts
> +      console.log('error loggin in', err);
console.error instead of .log when you log errors

2023-02-02 16:37 UTC, CiprianDraghici commented on src/providers/webviewProvider/webviewProvider.ts
> +      console.log('error sending transaction', err);
console.error

2023-02-02 16:37 UTC, CiprianDraghici commented on src/providers/webviewProvider/webviewProvider.ts
> +      console.log('error loggin in', err);
console.error

2023-02-02 16:40 UTC, CiprianDraghici requested changes
Please see my comments

2023-02-03 07:53 UTC, CiprianDraghici approved these changes

2023-02-03 08:04 UTC, CiprianDraghici approved these changes

2023-02-03 08:05 UTC, merged